name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --frozen-lockfile
      - run: npm run lint
  build frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --frozen-lockfile
      - run: cnpm build
