runtime: nodejs
env: flex

env_variables:
  DB_CLOUD_URI: 
  ENV: PROD
  URI_FRONTEND: https://peerpressure-366414.et.r.appspot.com

manual_scaling:
  instances: 1

network:
  session_affinity: true

service: communication-service